### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by YariKartoshe4ka** [chunqiuyiyu/sublime-svg-preview#4]
I wrote a [small plugin](https://github.com/YariKartoshe4ka/sublime-svg-viewer) to view svg as a picture too. Our plugins are quite similar in approach, but somewhat different in wrapper:
1. View images in a new tab against preview in popup (maybe not convenient with big images)
2. I think my plugin is more convenient in terms of extensibility
3. And possibility to viewing SVG as the image by default.

Is it possible for us to collaborate in order to combine our plugins in something very very beautiful?

**Comment by chunqiuyiyu** [comment]
@YariKartoshe4ka  Thanks for your suggestion. I think that your plugin is awesome, But I am busy with my work recently and have no time   to cooperate with you. I just add your plugin project in my README file.

**Comment by YariKartoshe4ka** [comment]
Very sad, I really don't mind working with someone on this project (because two is better than one), but it's your right
[Thank a lot](https://github.com/chunqiuyiyu/sublime-svg-preview/commit/d381760916786c120ac82484dfcedc1a8bd7204d)
Close this
